#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/mysql
- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL is started
  service:
    name: mysql
    state: started
    enabled: yes
